### ISSUE TITLE
Calculator - Too many interaction messages

### ISSUE THREAD

**Issue by SteadyStatus21** [AAA3A-AAA3A/AAA3A-cogs#2]
### What cog is this bug report for?

Calculator

### Describe the bug

The way the calculator works is by sending individual interaction messages back to the user, which I feel should instead be edited. is there a way to edit this. Thank you!

**Comment by AAA3A-AAA3A** [comment]
@SteadyStatus21 
Hello,
Of course, I would have preferred not to display any message. For interactions this cogs uses Dislash. A feature of it is to edit the message having the interaction. The problem is that it does not work and causes interaction failure for Discord. And the original message is also modified, already.
As you may know, Red 3.5 will use dpy2.  These spams will therefore be deleted when switching to this version, around May 1st. I am in the process of starting the migration.
Thanks for opening this issue.

**Comment by AAA3A-AAA3A** [comment]
Red 3.5 has not yet been released and will probably be released towards the end of July. I wanted to point out that the Calculator migration is complete for dpy2 and that the interactions work much better than when using Dislash.
