### ISSUE TITLE
[Autotraceback] Tracebacks not displayed automatically and add channel setting.

### ISSUE THREAD

**Issue by Xg4dam** [AAA3A-AAA3A/AAA3A-cogs#24]
### What cog is this bug report for?

autotraceback 

### Describe the bug

when errors occur, they aren't displayed automatically, and there's no configuration options to send the traceback to a certain channel

**Comment by AAA3A-AAA3A** [comment]
Hello,
What do you mean the traceback is not displayed automatically? (Please note that this is only if the **command was executed by a bot owner**).
Maybe I can add an option to choose the channel, but **that's not the point of the cog**. This cog is mainly intended for cog developers because it allows displaying errors directly after the command is executed instead of having to use the `[p]traceback` command. **Other cogs exist to do this.**
Have a nice day,
AAA3A

**Comment by Xg4dam** [comment]
I mean it doesn't display the message when there's an error, the only part to the cog is the traceback command as far as i can tell

**Comment by AAA3A-AAA3A** [comment]
It's weird. There is no error on the console? And it's a bot owner who executes the command with the error? This works on my two bots dpy1 and dpy2.

**Comment by Xg4dam** [comment]
Is the traceback only supposed to show up in the console or in the channel the command was executed in too?

**Comment by AAA3A-AAA3A** [comment]
I'm closing this issue as there have been no further replies for several months.
